### ISSUE TITLE
how to cite this package?

### ISSUE THREAD

**Issue by AlisaGU** [benmarwick/gsloid#1]
Hi,
I am new to this field. Your package helped me a lot. It's hard for me to describe this feeling.
But I don't know how to cite this work

**Comment by benmarwick** [comment]
Hello, Thanks for your question. I think the citation for this package should be something like this (according to the guidance [here](https://ropensci.org/blog/2021/11/16/how-to-cite-r-and-r-packages/)):

Marwick, B., L. Lisiecki, R. Spratt, M. Raymo (2021). gsloid: Global Sea Level and Oxygen Isotope Data. R package version 0.1.9000 https://CRAN.R-project.org/package=gsloid

And you should also cite the original data publications:

Lisiecki, L.E. and M.E. Raymo. 2005. A Pliocene-Pleistocene stack of 57 globally distributed benthic D18O records. Paleoceanography, Vol. 20, PA1003, https://doi.org/10.1029/2004PA001071

Spratt, Rachel M. and Lorraine E. Lisiecki 2016. A Late Pleistocene sea level stack. Climate of the Past. Vol. 12, 1079-1092, https://doi.org/10.5194/cp-12-1-2016

I hope that helps!
